services:
  - type: web
    name: lakshmipur-bostraloy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: ADMIN_EMAIL
        value: admin@lakshmipurbostraloy.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bostraloy-db
          property: connectionString

databases:
  - name: bostraloy-db
    databaseName: bostraloy
    plan: free
